version: "3.8"

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  api:
    build:
      context: .
      args:
        - BIN_FOLDER=api
    image: riot-api:latest
    links:
      - mongo
      - mongo-express
    environment:
      - MONGO_HOST=mongodb://root:example@mongo:27017/
      - MONGO_DATABASE=riot
      - MONGO_TEAMS_COLLECTION=teams
      - MONGO_GAMES_COLLECTION=games
      - MONGO_MAPPINGS_COLLECTION=mappings
      - MONGO_TOURNAMENTS_COLLECTION=tournaments
      - MONGO_LEAGUES_COLLECTION=leagues
      - MONGO_PLAYERS_COLLECTION=players
      - LISTEN_PORT=7755
      - LISTEN_HOST=api
      - LOG_VERBOSITY=-4
    ports:
      - "7755:7755"
    develop:
      watch:
        - action: rebuild
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum